### ISSUE TITLE
Cannot download from Vanguard

### ISSUE THREAD

**Issue by rkhwaja** [captin411/ofxclient#46]
Vanguard is returning an empty string as the body. Since around 7/19/2016, I think.

**Comment by jantman** [comment]
I can confirm this for me as well, since July 21, 2017 (I think @rkhwaja had the year wrong in his comment).

I run via cron every morning around 2AM Eastern. Vanguard had worked reliably since March through July 20th. From the 21st on, it's getting 0-byte responses.

**Comment by jantman** [comment]
Ok, I spent about an hour trying various things. The OFX statements that I manually download from Vanguard's site are still OFX version 102, but they include "INTU.USERID" and "INTU.BID" (FITID) fields in the signon, and have the userid in all uppercase. I tried changing the signon to those fields, adding the INTU.BID field, and various different APPVERs for QWIN (2200, 2300, 2400, 2500). I haven't been able to find anything that works. Sometime this week I'll call their tech support and see if I can get any usable information...

**Comment by rkhwaja** [comment]
Can anyone still download Vanguard ofxs? Maybe it's something to do with the accounts themselves. For instance, I haven't made the switch from mutual fund to brokerage accounts yet and my downloads don't work.

**Comment by MarkLodato** [comment]
I cannot. Stopped working just as @jantman said.

**Comment by rkhwaja** [comment]
If I download a new ofx file from the website, my account numbers have the prefix "0540-", whereas I've been using account numbers without that prefix. However, I tried adding the prefix when downloading through ofxclient but it still didn't download a valid ofx.

**Comment by jantman** [comment]
I found a [comment about the PocketSense](https://pocketsense.blogspot.com/2017/03/new-version-released.html?showComment=1501423318457#c1181103133737423582) software, which from what I can tell has a lot of code in common with ofxclient (I believe they're both descended from the same code, or something like that) confirming the Vanguard issue with that code as well.

The author of that code said that he figured out a workaround to fix Vanguard, and the problem seems to be that Vanguard has introduced and is now requiring the use of session cookies, which I'm not sure is really compliant in the OFX spec, but at least the author and one user of that package has confirmed the fix. See [this portion of the diff](https://gist.github.com/jantman/596ab49b2640e9c588865725e6d7e7f0#file-pocketsense_vanguard-diff-L111) for the fix they used; it seems to try the request once, and if it fails, it resends it with cookies returned in the failure message.

I'm going to try a similar fix in my fork and see if it works.

**Comment by jantman** [comment]
Ok, I have a quick fix that works. I'm working on getting it polished up and pushed up in a branch and PR now.

**Comment by jantman** [comment]
I have a PR open ( #47  ) with a fix that works for me, from the [vanguard-fix branch of my fork](https://github.com/jantman/ofxclient/tree/vanguard-fix). If anyone would like to give it a try, you can install from that branch with: ``pip install git+https://github.com/jantman/ofxclient.git@vanguard-fix#egg=ofxclient``

**Comment by rkhwaja** [comment]
Works for me - thanks. I didn't have to make any changes to my login details.

**Comment by scanlom** [comment]
Good stuff, works now - had to use caps for my username

**Comment by captin411** [comment]
Thanks for the fix. I’m on vacation for a few more days and this is the
first (and only) internet access I’ll have (yes... that far off the grid).
I’ll merge it when I get back.

**Comment by MarkLodato** [comment]
Friendly ping. Any chance to merge this fix? Thanks!
